import { TimeSeries } from 'pond-ts';
import { BAR_INTERVAL_MS, type BarInterval, type Instrument } from './types.js';

/**
 * Deterministic price fixtures. Until the real data API lands (Tidal pulls bars
 * over HTTP — see `@tidal/app`), the app charts synthetic OHLCV generated by a
 * **seeded** random walk so the same `(symbol, seed)` always yields the same
 * series. That keeps stories, tests, and the dev app showing stable data, and
 * gives the chart layer something realistic to render. Returns a pond
 * `TimeSeries` — the same carrier the HTTP data source will hand back, so the
 * UI never knows whether prices are real or generated.
 */

/** mulberry32 — a tiny, fast, seedable PRNG. Deterministic per seed so fixtures
 *  are reproducible (real randomness would make tests flaky and stories drift). */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** A standard-normal sample (Box–Muller) from a uniform generator — daily
 *  returns are roughly Gaussian, so the walk reads like a real price path. */
function gaussian(rng: () => number): number {
  let u = 0;
  let v = 0;
  while (u === 0) u = rng();
  while (v === 0) v = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

export interface PriceSeriesOptions {
  /** Number of bars to generate. */
  bars?: number;
  /** Bar interval (spacing). Default daily. */
  interval?: BarInterval;
  /** Timestamp (ms) of the LAST bar; earlier bars step back by the interval.
   *  Defaults to a fixed epoch so series are fully deterministic (no clock). */
  endMs?: number;
  /** Opening price of the first bar. */
  startPrice?: number;
  /** Per-bar return volatility (std-dev of the log return). Default 2%. */
  volatility?: number;
  /** Per-bar drift (mean log return). Default slight positive. */
  drift?: number;
  /** PRNG seed. Same seed ⇒ identical series. Defaults from the symbol. */
  seed?: number;
}

/** A stable seed derived from a symbol, so `AAPL` always looks like `AAPL`
 *  without the caller tracking seeds. */
function symbolSeed(symbol: string): number {
  let h = 2166136261;
  for (let i = 0; i < symbol.length; i++) {
    h ^= symbol.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** A fixed reference epoch (2024-01-01T00:00:00Z) so generated series don't
 *  depend on the wall clock — reproducible across machines and CI. */
const REFERENCE_EPOCH_MS = 1_704_067_200_000;

/** The schema of every Tidal price series — `time`-keyed OHLCV. Shared by the
 *  fixture and the HTTP data source so both produce identically-shaped series
 *  the chart layer can consume without branching. */
export const PRICE_SCHEMA = [
  { name: 'time', kind: 'time' },
  { name: 'open', kind: 'number' },
  { name: 'high', kind: 'number' },
  { name: 'low', kind: 'number' },
  { name: 'close', kind: 'number' },
  { name: 'volume', kind: 'number' },
] as const;

/** A row of a price series in column order: `[time, open, high, low, close,
 *  volume]`. The wire format the data layer normalizes into. */
export type PriceRow = [number, number, number, number, number, number];

/** A Tidal price series — a `time`-keyed OHLCV pond `TimeSeries`. The single
 *  carrier type the data layer returns and the chart layer renders. */
export type PriceSeries = TimeSeries<typeof PRICE_SCHEMA>;

/** Build a {@link PriceSeries} from raw OHLCV rows. The one place the price
 *  `TimeSeries` is constructed — fixture, HTTP source, and the real ticker-history
 *  adapter all funnel through here. Uses the **columnar** ingress (gap-tolerant,
 *  `sort:true`) so a non-finite cell reads as a gap rather than being rejected —
 *  real data can carry the occasional missing OHLCV cell. */
export function buildPriceSeries(name: string, rows: readonly PriceRow[]): PriceSeries {
  return TimeSeries.fromColumns({
    name,
    schema: PRICE_SCHEMA,
    columns: {
      time: rows.map((r) => r[0]),
      open: rows.map((r) => r[1]),
      high: rows.map((r) => r[2]),
      low: rows.map((r) => r[3]),
      close: rows.map((r) => r[4]),
      volume: rows.map((r) => r[5]),
    },
    sort: true,
  });
}

/**
 * Generate a deterministic OHLCV price series for an instrument as a pond
 * `TimeSeries` (schema: `time`, `open`, `high`, `low`, `close`, `volume`).
 * Close-to-close follows a seeded geometric random walk; each bar's high/low
 * bracket its open/close with a little intrabar noise, and volume scales with
 * the bar's range.
 */
export function generatePriceSeries(
  instrument: Instrument,
  options: PriceSeriesOptions = {},
): PriceSeries {
  const {
    bars = 180,
    interval = '1d',
    endMs = REFERENCE_EPOCH_MS,
    startPrice = instrument.kind === 'crypto' ? 30000 : instrument.kind === 'fx' ? 1.1 : 150,
    volatility = instrument.kind === 'crypto' ? 0.04 : 0.02,
    drift = 0.0004,
    seed = symbolSeed(instrument.symbol),
  } = options;

  const stepMs = BAR_INTERVAL_MS[interval];
  const rng = mulberry32(seed);

  const rows: PriceRow[] = [];
  let close = startPrice;
  for (let i = bars - 1; i >= 0; i--) {
    const time = endMs - i * stepMs;
    const open = close;
    const ret = drift + volatility * gaussian(rng);
    close = Math.max(0.01, open * Math.exp(ret));
    const hi = Math.max(open, close) * (1 + Math.abs(volatility * gaussian(rng)) * 0.5);
    const lo = Math.min(open, close) * (1 - Math.abs(volatility * gaussian(rng)) * 0.5);
    const range = hi - lo;
    const volume = Math.round((1 + range / open) * 1_000_000 * (0.5 + rng()));
    rows.push([time, round2(open), round2(hi), round2(lo), round2(close), volume]);
  }

  return buildPriceSeries(instrument.symbol, rows);
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

/** A small demo universe — enough to populate the instrument switcher and the
 *  dashboard before the real data API is wired. */
export const DEMO_INSTRUMENTS: Instrument[] = [
  { symbol: 'AAPL', name: 'Apple Inc.', kind: 'equity' },
  { symbol: 'MSFT', name: 'Microsoft Corp.', kind: 'equity' },
  { symbol: 'BTC-USD', name: 'Bitcoin / US Dollar', kind: 'crypto' },
  { symbol: 'EUR-USD', name: 'Euro / US Dollar', kind: 'fx' },
  { symbol: 'SPX', name: 'S&P 500 Index', kind: 'index' },
];
