import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The catalog's families come straight from their folders, in the order the
 * study menu lists them (each folder's `_category_.json` carries its position),
 * so adding a study page needs no edit here.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      items: ['packages/core', 'packages/chart', 'packages/terminal'],
    },
    {
      // The pond-ts packages tidal-ts is built on, on pond-ts's own site.
      type: 'category',
      label: 'Built on pond-ts',
      collapsed: false,
      items: [
        { type: 'link', label: 'pond-ts (core)', href: 'https://pond-ts.org/docs/pond-ts' },
        { type: 'link', label: '@pond-ts/financial', href: 'https://pond-ts.org/docs/financial' },
        { type: 'link', label: '@pond-ts/charts', href: 'https://pond-ts.org/docs/charts' },
      ],
    },
    {
      type: 'category',
      label: 'Study catalog',
      collapsed: false,
      link: { type: 'doc', id: 'studies' },
      items: [{ type: 'autogenerated', dirName: 'studies' }],
    },
  ],
};

export default sidebars;
