import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The catalog's families come straight from their folders, in the order the
 * study menu lists them (each folder's `_category_.json` carries its position),
 * so adding a study page needs no edit here.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Packages',
      collapsed: false,
      items: ['packages/core', 'packages/chart', 'packages/terminal'],
    },
    {
      type: 'category',
      label: 'Study catalog',
      collapsed: false,
      link: { type: 'doc', id: 'studies' },
      items: [{ type: 'autogenerated', dirName: 'studies' }],
    },
  ],
};

export default sidebars;
