import { studyCatalog } from '@tidal-ts/core';
import { STUDY_DOCS } from './docs/index.js';
import { FAMILIES } from './families.js';

/**
 * The docs site's study pages (`website/docs/studies/`), as the files they must
 * be: one folder per family, one MDX page per study, each rendering the same
 * `StudyPage` the workshop does. They are committed so the site builds from
 * plain files, and `sitePages.test.ts` fails when they drift from the registry
 * — `WRITE_SITE_PAGES=1 pnpm --filter @tidal-ts/chart test` rewrites them.
 *
 * Only the routing lives in the files. Everything a reader sees comes from the
 * registry and `docs/`, at render time.
 */

/** A YAML string the way the repo's prettier writes one: single-quoted, unless
 *  the text holds more single quotes than double ones. */
const yaml = (text: string): string => {
  const singles = text.split("'").length - 1;
  const doubles = text.split('"').length - 1;
  return singles > doubles ? JSON.stringify(text) : `'${text.replace(/'/g, "''")}'`;
};

const firstSentence = (text: string): string => /^.*?[.!?](?=\s|$)/.exec(text)?.[0] ?? text;

/** `{ relativePath: contents }`, paths relative to `website/docs/studies/`. */
export function sitePages(): Record<string, string> {
  const files: Record<string, string> = {};
  const catalog = studyCatalog();
  FAMILIES.forEach((f, i) => {
    files[`${f.family}/_category_.json`] =
      JSON.stringify({ label: f.label, position: i + 1, collapsed: true, link: null }, null, 2) +
      '\n';
    const ops = catalog
      .filter((s) => s.family === f.family)
      .map((s) => s.op as string)
      .sort((a, b) => (STUDY_DOCS[a]?.name ?? a).localeCompare(STUDY_DOCS[b]?.name ?? b, 'en'));
    ops.forEach((op, j) => {
      const doc = STUDY_DOCS[op];
      if (!doc) return; // studyDocs.test.ts names the missing page
      files[`${f.family}/${op}.mdx`] = [
        '---',
        `title: ${yaml(doc.name)}`,
        `description: ${yaml(firstSentence(doc.what))}`,
        // Explicit, because a page named after its folder (`momentum/momentum`)
        // would otherwise be taken as the folder's index page.
        `slug: ${op}`,
        `sidebar_position: ${j + 1}`,
        'hide_title: true',
        'hide_table_of_contents: true',
        '---',
        '',
        '{/* Generated by packages/chart/.storybook/studies/sitePages.ts — edit the prose in docs/ there. */}',
        '',
        "import { Study } from '@site/src/components/Study';",
        '',
        `<Study op="${op}" />`,
        '',
      ].join('\n');
    });
  });
  return files;
}
